<?php


namespace App\Command;


use App\Service\BChain;
use Symfony\Component\Console\Command\Command;
use Symfony\Component\Console\Input\InputArgument;
use Symfony\Component\Console\Input\InputInterface;
use Symfony\Component\Console\Output\OutputInterface;
use Symfony\Component\Process\Process;

class TradingCommand extends Command
{
    private $blockchain;

    public function __construct(string $name = null, BChain $blockChain)
    {
        $this->blockchain = $blockChain;
        parent::__construct($name);
    }

    protected static $defaultName = "app:get-spread";

    protected function configure()
    {
        parent::configure(); // TODO: Change the autogenerated stub
        $this->setDescription('Get current change of two currencies');

        $this->setHelp('This command allow a user to get information about two currencies');

        $this->addArgument('signatureWallet', InputArgument::REQUIRED, 'Signature of the wallet' );
        $this->addArgument('baseCurrency', InputArgument::REQUIRED, 'Base currency' );
        $this->addArgument('targetCurrency', InputArgument::REQUIRED, 'Target currency' );
    }

    protected function execute(InputInterface $input, OutputInterface $output)
    {
        $sign = $input->getArgument('signatureWallet');
        $baseCurrency = $input->getArgument('baseCurrency');
        $targetCurrency = $input->getArgument('targetCurrency');

        $cmd = new Process("echo 'Wallet : \n Signature : $sign - base currency : $baseCurrency - target Currency : $targetCurrency' >> /home/lionel/projects/trade_cube/crontab.out");
        $cmd->run();

        return 0;
    }
}